# Generated by Django 5.2.8 on 2025-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcf_file', models.FileField(upload_to='uploads/vcf/')),
                ('gff_file', models.FileField(blank=True, null=True, upload_to='uploads/gff/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window_size', models.IntegerField(default=1000, help_text='Window size for density analysis (bp)')),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('plot_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_density', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
