# Generated by Django 5.2.8 on 2025-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='annotation_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
