# Generated by Django 5.2.8 on 2025-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_annotation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='window_size',
            field=models.IntegerField(default=1000, help_text='Tamanho da janela para análise de densidade (bp)'),
        ),
    ]
