# Generated by Django 5.2.7 on 2025-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysis_error_message_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='reference_file',
            field=models.FileField(blank=True, help_text='Arquivo FASTA do genoma de referência (opcional)', null=True, upload_to='uploads/ref/'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=20),
        ),
    ]
