# Generated by Django 5.2.8 on 2025-12-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_reference_file_alter_analysis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='reference_file',
        ),
        migrations.AddField(
            model_name='analysis',
            name='reference_genome',
            field=models.CharField(choices=[('hg38', 'Human (hg38)'), ('hg19', 'Human (hg19)')], default='hg38', max_length=10),
        ),
    ]
