# Generated by Django 5.2.7 on 2025-12-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_analysis_reference_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='reference_genome',
        ),
        migrations.AddField(
            model_name='analysis',
            name='genome_build',
            field=models.CharField(choices=[('hg38', 'Human (GRCh38/hg38)'), ('hg19', 'Human (GRCh37/hg19)')], default='hg38', max_length=10),
        ),
    ]
