# Generated by Django 5.2.7 on 2025-12-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_analysis_reference_genome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='genome_build',
        ),
        migrations.AddField(
            model_name='analysis',
            name='reference_file',
            field=models.FileField(blank=True, help_text='Arquivo FASTA do genoma de referência (obrigatório para visualização no IGV)', null=True, upload_to='uploads/reference/'),
        ),
    ]
