# Generated by Django 5.2.7 on 2025-12-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_analysis_genome_build_analysis_reference_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reference_file',
            field=models.FileField(blank=True, help_text='Arquivo FASTA do genoma de referência (obrigatório para visualização no IGV)', null=True, upload_to='uploads/fasta/'),
        ),
    ]
