# Generated by Django 5.2.7 on 2025-12-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_analysis_reference_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='reference_file',
        ),
        migrations.AddField(
            model_name='analysis',
            name='plot_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
