# Generated by Django 5.2.7 on 2025-12-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_analysis_reference_file_analysis_plot_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='reference_file',
            field=models.FileField(blank=True, help_text='Arquivo FASTA de referência (opcional)', null=True, upload_to='uploads/fasta/'),
        ),
    ]
